language: objective-c
sudo: true
osx_image: xcode9.3
cache: 
  - bundler
  - cocoapods
rvm:  
  - 2.1.0
env:
    global:
        - LC_CTYPE=en_US.UTF-8
        - LANG=en_US.UTF-8

matrix:
  include:
    - env: NAME='[ObjC] iOS 10.3.1 32bit' SCHEME='"iOS Tests (ObjC)"' DESTINATIONS='-destination "platform=iOS Simulator,name=iPhone 6s Plus,OS=10.3.1" -destination "platform=iOS Simulator,name=iPhone 6s Plus,OS=10.3.1" -destination "platform=iOS Simulator,name=iPhone 7 Plus,OS=10.3.1" -destination "platform=iOS Simulator,name=iPad Pro (12.9 inch),OS=10.3.1"' ARCHS=i386
    - env: NAME='[ObjC] iOS 10.3.1 64bit' SCHEME='"iOS Tests (ObjC)"' DESTINATIONS='-destination "platform=iOS Simulator,name=iPhone 6s Plus,OS=10.3.1" -destination "platform=iOS Simulator,name=iPhone 6s Plus,OS=10.3.1" -destination "platform=iOS Simulator,name=iPhone 7 Plus,OS=10.3.1" -destination "platform=iOS Simulator,name=iPad Pro (12.9 inch),OS=10.3.1"' ARCHS=x86_64
    - env: NAME='[ObjC] iOS 11.3 32bit' SCHEME='"iOS Tests (ObjC)"' DESTINATIONS='-destination "platform=iOS Simulator,name=iPhone 6s Plus,OS=11.3" -destination "platform=iOS Simulator,name=iPhone 6s Plus,OS=11.3" -destination "platform=iOS Simulator,name=iPhone 7 Plus,OS=11.3" -destination "platform=iOS Simulator,name=iPad Pro (12.9 inch),OS=11.3"' ARCHS=i386
    - env: NAME='[ObjC] iOS 11.3 64bit' SCHEME='"iOS Tests (ObjC)"' DESTINATIONS='-destination "platform=iOS Simulator,name=iPhone 6s Plus,OS=11.3" -destination "platform=iOS Simulator,name=iPhone 6s Plus,OS=11.3" -destination "platform=iOS Simulator,name=iPhone 7 Plus,OS=11.3" -destination "platform=iOS Simulator,name=iPad Pro (12.9 inch),OS=11.3"' ARCHS=x86_64
    - env: NAME='[ObjC] tvOS 10.2 64bit' SCHEME='"tvOS Tests (ObjC)"' DESTINATIONS='-destination "platform=tvOS Simulator,name=Apple TV 4K (at 1080p),OS=10.2"' ARCHS=x86_64
    - env: NAME='[ObjC] tvOS 10.2 64bit' SCHEME='"tvOS Tests (ObjC)"' DESTINATIONS='-destination "platform=tvOS Simulator,name=Apple TV 4K (at 1080p),OS=11.3"' ARCHS=x86_64
    - env: NAME='[ObjC] macOS' SCHEME='"OSX Tests (ObjC)"' DESTINATIONS='-destination "platform=macOS"' ARCHS=x86_64

before_install:
  - sudo gem install cocoapods -v '1.5.0'

script:
  - set -o pipefail
  - xcodebuild -workspace ./PubNub.xcworkspace -scheme $SCHEME $DESTINATIONS ARCHS=$ARCHS clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -f `xcpretty-travis-formatter`

after_failure:
 - cat -n $TMPDIR/com.apple.dt.XCTest-status/Session*.log
 - cat -n ~/Library/Logs/DiagnosticReports/xctest*.crash

notifications:
  flowdock:
    secure: kOxa/6eB6+bQumvYSh7yf/uPNQ5xRastjSkRbUrqVbYEiMiguCuoe8xkmU5JJxmNMpvFjYL9yowPo9LELMceVsWVflNEEWFQE5sJe9qifZu/SpOD8RUWfHmZ2jZBELmnLSDSAIxaAjQMb1LEedkBHGMVJknbb+DRs4fT31ilMUM=
