podfile: Tests/Podfile
language: objective-c
osx_image: xcode11.3
os: osx

cache: 
  cocoapods: true

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

before_script:
  - sudo gem install xcpretty
  - ./.travis/repo-scripts/create-configuration.sh

stages:
  - name: test

jobs:
  include:
    - stage: "test"
      name: "[iOS] Mocked Integration test"
      script: ./.travis/repo-scripts/tests-runner.sh ios
    - name: "[macOS] Mocked Integration test"
      script: ./.travis/repo-scripts/tests-runner.sh macos
    - name: "[tvOS] Mocked Integration test"
      script: ./.travis/repo-scripts/tests-runner.sh tvos

after_failure:
 - cat -n ~/Library/Logs/scan/*
 - cat -n $TMPDIR/com.apple.dt.XCTest-status/Session*.log
 - cat -n ~/Library/Logs/DiagnosticReports/xctest*.crash