language: objective-c
sudo: true
osx_image: xcode9.3
cache: 
  - bundler
  - cocoapods
rvm:  
  - 2.1.0
env:
    global:
        - LC_CTYPE=en_US.UTF-8
        - LANG=en_US.UTF-8

matrix:
  include:
    - env: NAME='[ObjC] iOS' SCHEME='iOS Tests (ObjC)' DESTINATION='platform=iOS Simulator,name=iPhone 7 Plus,OS=11.3'
    - env: NAME='[ObjC] tvOS' SCHEME='tvOS Tests (ObjC)' DESTINATION='platform=tvOS Simulator,name=Apple TV 4K (at 1080p),OS=11.3'
    - env: NAME='[ObjC] macOS' SCHEME='OSX Tests (ObjC)' DESTINATION='-platform=macOS'

before_install:
  - sudo gem install cocoapods -v '1.5.0'
  - sudo gem install xcpretty
  - sudo gem install xcpretty-travis-formatter

script:
  - set -o pipefail && xcodebuild -workspace ./PubNub.xcworkspace -scheme "${SCHEME}" -destination "${DESTINATION}" clean build test | xcpretty -f `xcpretty-travis-formatter`

after_failure:
 - cat -n $TMPDIR/com.apple.dt.XCTest-status/Session*.log
 - cat -n ~/Library/Logs/DiagnosticReports/xctest*.crash

notifications:
  flowdock:
    secure: kOxa/6eB6+bQumvYSh7yf/uPNQ5xRastjSkRbUrqVbYEiMiguCuoe8xkmU5JJxmNMpvFjYL9yowPo9LELMceVsWVflNEEWFQE5sJe9qifZu/SpOD8RUWfHmZ2jZBELmnLSDSAIxaAjQMb1LEedkBHGMVJknbb+DRs4fT31ilMUM=
